// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihkyfekymffazdoxfjbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imloa3lmZWt5bWZmYXpkb3hmamJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTU5NDYsImV4cCI6MjA3MDk5MTk0Nn0.UcB0yQ61TylvCm6uBdT7l069JgUCN_hg7vpN9owPC1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});